### ISSUE TITLE
Cannot deploy simple stream

### ISSUE THREAD

**Issue by channing-jackson** [spring-cloud/spring-cloud-deployer-cloudfoundry#126]
Hi all. 

Using: 
- spring-cloud-dataflow-server-cloudfoundry-1.1.0.RELEASE

Configured with properties (from config server binding): 
Git repo file: app-channing.properties
```
spring.cloud.deployer.cloudfoundry.url=https://api.scp.company.com
spring.cloud.deployer.cloudfoundry.org=orgname
spring.cloud.deployer.cloudfoundry.space=channing
spring.cloud.deployer.cloudfoundry.domain=scp.company.com
spring.cloud.deployer.cloudfoundry.username=username
spring.cloud.deployer.cloudfoundry.password={cipher}q4qafdafa34896897cf7bf3407181be
spring.cloud.deployer.cloudfoundry.skipSslValidation=false
spring.cloud.deployer.cloudfoundry.stream.services=rabbit,config-server
spring.cloud.deployer.cloudfoundry.task.services=mysql
spring.cloud.deployer.cloudfoundry.stream.enableRandomAppNamePrefix=false
spring.cloud.deployer.cloudfoundry.stream.memory=768
spring.cloud.deployer.cloudfoundry.stream.disk=256
```
Environment variables are: 
```
ENCRYPT_KEY=<secret>
JAVA_OPTS=-DhttpKeepAlive=false
SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_APP_NAME_PREFIX=channing
SPRING_APPLICATION_NAME=app
SPRING_PROFILES_ACTIVE=channing
```

Creating just the simple ticktock stream, I get the following errors in the log: 

```
2017-01-26T12:09:10.065-07:00 [APP/PROC/WEB/0] [OUT] 2017-01-26 19:09:10.065 ERROR 20 --- [nio-8080-exec-5] o.s.c.d.s.c.StreamDeploymentController : Exception when deploying the app StreamAppDefinition [streamName=ticktock, name=log, registeredAppName=log, properties={spring.cloud.stream.bindings.input.destination=ticktock.time, spring.cloud.stream.bindings.input.group=ticktock}]: App channing-ticktock-log is already deployed with state error
2017-01-26T12:09:10.065-07:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:166) ~[reactor-core-3.0.4.RELEASE.jar!/:3.0.4.RELEASE]
2017-01-26T12:09:10.065-07:00 [APP/PROC/WEB/0] [OUT] java.lang.IllegalStateException: App channing-ticktock-log is already deployed with state error
```

And...

```
2017-01-26T12:09:11.548-07:00 [APP/PROC/WEB/0] [OUT] 2017-01-26 19:09:11.548 ERROR 20 --- [nio-8080-exec-5] o.s.c.d.s.c.StreamDeploymentController : Exception when deploying the app StreamAppDefinition [streamName=ticktock, name=time, registeredAppName=time, properties={spring.cloud.stream.bindings.output.destination=ticktock.time, trigger.fixed-delay=30, spring.cloud.stream.bindings.output.producer.requiredGroups=ticktock}]: App channing-ticktock-time is already deployed with state error
2017-01-26T12:09:11.548-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.deployer.spi.cloudfoundry.CloudFoundryAppDeployer.lambda$deploy$0(CloudFoundryAppDeployer.java:95) ~[spring-cloud-deployer-cloudfoundry-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
2017-01-26T12:09:11.548-07:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:316) ~[reactor-core-3.0.4.RELEASE.jar!/:3.0.4.RELEASE]
2017-01-26T12:09:11.548-07:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxResume$ResumeSubscriber.onNext(FluxResume.java:71) ~[reactor-core-3.0.4.RELEASE.jar!/:3.0.4.RELEASE]
2017-01-26T12:09:11.548-07:00 [APP/PROC/WEB/0] [OUT] java.lang.IllegalStateException: App channing-ticktock-time is already deployed with state error
```

I'm not a newbie with Spring Cloud Dataflow, nor with PCF, so I'm confounded why this is happening.  Perhaps there is some compatibility issue, or something else going on that I'm missing because I *think* I've done everything correctly.  This worked fine with the v1.1.0-M1 release.  The only difference there being that for the milestone release, I added the spring-cloud-config-starter-binding so I could bind the application with spring cloud config server.  With v1.1.0.RELEASE I did not do that, because I read in the documentation that binding is already there.  

Based on the /management/env endpoint information for the server application, my config is being read properly from the properties file in my git repo.

Any help would be greatly appreciated.

**Comment by markpollack** [comment]
This looks to be a side effect that for some unknown reason calls to get the status of an application are not reliable. We have added a retry mechanism to compensate for this which has helped some in some cases, for example with `app list` when we compute the state of the stream.

ATM, if we don't get an answer from CF about the status of an app, we set the app's status to be 'error', meaning a system error occurred trying to determine deployment status.  We only try to deploy the app if we know for sure the app is not present. 

So a couple things we need to fix.

* The log message isn't clear at all
* We should go ahead and try to deploy anyway and hope for the best.

Apologies about this, it will be an intermittent issue and I can't think of a workaround. 

There are several issues we are tracking down which aren't yet on the GH issues page.  We will get those added shortly.  I will let you know when we have a snapshot release that you can try and we will be making a 1.1.1 release ASAP to fix this.

**Comment by sabbyanandan** [comment]
Hi, @channing-jackson: We have released [1.1.1.RELEASE](https://spring.io/blog/2017/02/22/spring-cloud-data-flow-for-cloud-foundry-1-1-1-maintenance-release-available) and that includes significant stability improvements - please try it out and let us know if you find any anomalies.

**Comment by channing-jackson** [comment]
Thank you @sabbyanandan for the heads up!  I will install and check out version 1.1.1.RELEASE when I get a chance, and loop back with any feedback.

**Comment by channing-jackson** [comment]
Hi @sabbyanandan - I'm happy to report that my original issues with instability as it related to deploying a stream seem to have been resolved.   Thanks to you and the rest of the Pivotal team.
