### ISSUE TITLE
Deployer intermittently returns AppStatus with 0 instances for deployed app

### ISSUE THREAD

**Issue by dturanski** [spring-cloud/spring-cloud-deployer-cloudfoundry#342]
This is causing `NamedChannelTests` and others in `spring-cloud-dataflow-acceptance-tests` to fail intermittently. Need to investigate further what is causing this.  At a minimum, the deployer should throw an exception whenever this happens.

**Comment by dturanski** [comment]
```java.lang.IllegalStateException: Unable to get available urls for stream HTTP-SOURCE-1= http > :MANY-TO-ONE-DESTINATION
	at org.springframework.cloud.dataflow.acceptance.test.NamedChannelTests.deployStream(NamedChannelTests.java:88)
	at org.springframework.cloud.dataflow.acceptance.test.NamedChannelTests.deployHttp(NamedChannelTests.java:104)
	at org.springframework.cloud.dataflow.acceptance.test.NamedChannelTests.manyToOneTest(NamedChannelTests.java:59)
```

**Comment by dturanski** [comment]
```
java.lang.IllegalStateException: Unable to get available urls for stream TICKTOCK= time | log
	at org.springframework.cloud.dataflow.acceptance.test.TickTockTests.tickTockTests(TickTockTests.java:53)
```

**Comment by sabbyanandan** [comment]
@dturanski: Do we still see these failures?

**Comment by dturanski** [comment]
I believe this has been fixed by decreasing a cache expiration timeout in the deployer.
