### ISSUE TITLE
Launching task throws java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-deployer-cloudfoundry#70]
When launching task on CF, below exception is thrown:

It looks like ListSpaceResponse has couple of SpaceResources when MonoSingle subscriber expects one item.
When debugging I see the following response:

```
ListSpacesResponse{nextUrl=null, previousUrl=null, resources=[SpaceResource{entity=SpaceEntity{allowSsh=true, applicationEventsUrl=/v2/spaces/f7005c0f-d261-49a0-b446-3c9484eb4d43/app_events, applicationsUrl=/v2/spaces/f7005c0f-d261-49a0-b446-3c9484eb4d43/apps, auditorsUrl=/v2/spaces/f7005c0f-d261-49a0-b446-3c9484eb4d43/auditors, developersUrl=/v2/spaces/f7005c0f-d261-49a0-b446-3c9484eb4d43/developers, domainsUrl=/v2/spaces/f7005c0f-d261-49a0-b446-3c9484eb4d43/domains, eventsUrl=/v2/spaces/f7005c0f-d261-49a0-b446-3c9484eb4d43/events, managersUrl=/v2/spaces/f7005c0f-d261-49a0-b446-3c9484eb4d43/managers, name=development, organizationId=3f308b42-a407-4aea-bf77-d064149339ad, organizationUrl=/v2/organizations/3f308b42-a407-4aea-bf77-d064149339ad, routesUrl=/v2/spaces/f7005c0f-d261-49a0-b446-3c9484eb4d43/routes, securityGroupsUrl=/v2/spaces/f7005c0f-d261-49a0-b446-3c9484eb4d43/security_groups, serviceInstancesUrl=/v2/spaces/f7005c0f-d261-49a0-b446-3c9484eb4d43/service_instances, spaceQuotaDefinitionId=null}, metadata=Metadata{createdAt=2014-08-28T17:17:26Z, id=f7005c0f-d261-49a0-b446-3c9484eb4d43, updatedAt=null, url=/v2/spaces/f7005c0f-d261-49a0-b446-3c9484eb4d43}}, SpaceResource{entity=SpaceEntity{allowSsh=true, applicationEventsUrl=/v2/spaces/37fea686-46f1-40f6-b556-7bc261378669/app_events, applicationsUrl=/v2/spaces/37fea686-46f1-40f6-b556-7bc261378669/apps, auditorsUrl=/v2/spaces/37fea686-46f1-40f6-b556-7bc261378669/auditors, developersUrl=/v2/spaces/37fea686-46f1-40f6-b556-7bc261378669/developers, domainsUrl=/v2/spaces/37fea686-46f1-40f6-b556-7bc261378669/domains, eventsUrl=/v2/spaces/37fea686-46f1-40f6-b556-7bc261378669/events, managersUrl=/v2/spaces/37fea686-46f1-40f6-b556-7bc261378669/managers, name=development, organizationId=b5e2992c-a7ba-4fc9-811b-b38b0a42b4a1, organizationUrl=/v2/organizations/b5e2992c-a7ba-4fc9-811b-b38b0a42b4a1, routesUrl=/v2/spaces/37fea686-46f1-40f6-b556-7bc261378669/routes, securityGroupsUrl=/v2/spaces/37fea686-46f1-40f6-b556-7bc261378669/security_groups, serviceInstancesUrl=/v2/spaces/37fea686-46f1-40f6-b556-7bc261378669/service_instances, spaceQuotaDefinitionId=null}, metadata=Metadata{createdAt=2016-08-08T21:13:12Z, id=37fea686-46f1-40f6-b556-7bc261378669, updatedAt=null, url=/v2/spaces/37fea686-46f1-40f6-b556-7bc261378669}}], totalPages=1, totalResults=2}
```

```
java.lang.IndexOutOfBoundsException: Source emitted more than one item
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onNext(MonoSingle.java:130) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:636) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:511) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onSubscribe(FluxFlatMap.java:994) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:95) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:59) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:360) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.MonoFlatMap$FlattenSubscriber$InnerSubscriber.onNext(MonoFlatMap.java:195) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:362) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:595) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onNext(FluxFlattenIterable.java:220) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxBuffer$BufferExactSubscriber.onComplete(FluxBuffer.java:182) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:177) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:96) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxBuffer.subscribe(FluxBuffer.java:75) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxFlattenIterable.subscribe(FluxFlattenIterable.java:103) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.MonoFlatMap$FlattenSubscriber.onNext(MonoFlatMap.java:158) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxResume$ResumeSubscriber.onNext(FluxResume.java:75) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:173) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:131) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.Operators$DeferredScalarSubscriber.complete(Operators.java:797) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.MonoThenApply$MonoThenApplyManager$SecondSubscriber.onNext(MonoThenApply.java:204) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:125) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.onNext(FluxUsing.java:320) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:115) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:390) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.Operators$DeferredScalarSubscriber.complete(Operators.java:797) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.MonoReduce$ReduceSubscriber.onComplete(MonoReduce.java:152) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:157) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnPipeline.onComplete(FluxSubscribeOn.java:137) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.ipc.netty.common.NettyChannelHandler$InboundSink.drain(NettyChannelHandler.java:696) ~[reactor-netty-0.5.0.M2.jar!/:na]
	at reactor.ipc.netty.common.NettyChannelHandler$InboundSink.request(NettyChannelHandler.java:772) ~[reactor-netty-0.5.0.M2.jar!/:na]
	at reactor.core.publisher.Operators$DeferredSubscription.set(Operators.java:598) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnPipeline.onSubscribe(FluxSubscribeOn.java:117) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.ipc.netty.common.NettyChannelHandler.subscribe(NettyChannelHandler.java:543) ~[reactor-netty-0.5.0.M2.jar!/:na]
	at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:59) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.publisher.FluxSubscribeOn$SourceSubscribeTask.run(FluxSubscribeOn.java:235) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at reactor.core.scheduler.ExecutorScheduler$ExecutorTrackedRunnable.run(ExecutorScheduler.java:134) ~[reactor-core-3.0.0.RC1.jar!/:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor.safeExecute(SingleThreadEventExecutor.java:451) ~[netty-all-4.1.3.Final.jar!/:4.1.3.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418) ~[netty-all-4.1.3.Final.jar!/:4.1.3.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:401) ~[netty-all-4.1.3.Final.jar!/:4.1.3.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877) ~[netty-all-4.1.3.Final.jar!/:4.1.3.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_20]
```

**Comment by ericbottard** [comment]
This happens when the account has several orgs and the same named space in those orgs (the lookup of spaceId doesn't take the org into account)
